package com.notiificaciones.push.domain.mysql;

public class Key {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.auth
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private String auth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.id_subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private Integer idSubscripcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key.p256dh
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private String p256dh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.id
     *
     * @return the value of key.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.id
     *
     * @param id the value for key.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.auth
     *
     * @return the value of key.auth
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.auth
     *
     * @param auth the value for key.auth
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setAuth(String auth) {
        this.auth = auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.id_subscripcion
     *
     * @return the value of key.id_subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public Integer getIdSubscripcion() {
        return idSubscripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.id_subscripcion
     *
     * @param idSubscripcion the value for key.id_subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setIdSubscripcion(Integer idSubscripcion) {
        this.idSubscripcion = idSubscripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key.p256dh
     *
     * @return the value of key.p256dh
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public String getP256dh() {
        return p256dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key.p256dh
     *
     * @param p256dh the value for key.p256dh
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setP256dh(String p256dh) {
        this.p256dh = p256dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Key other = (Key) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAuth() == null ? other.getAuth() == null : this.getAuth().equals(other.getAuth()))
            && (this.getIdSubscripcion() == null ? other.getIdSubscripcion() == null : this.getIdSubscripcion().equals(other.getIdSubscripcion()))
            && (this.getP256dh() == null ? other.getP256dh() == null : this.getP256dh().equals(other.getP256dh()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAuth() == null) ? 0 : getAuth().hashCode());
        result = prime * result + ((getIdSubscripcion() == null) ? 0 : getIdSubscripcion().hashCode());
        result = prime * result + ((getP256dh() == null) ? 0 : getP256dh().hashCode());
        return result;
    }
}