package com.notiificaciones.push.domain.mysql;

public class Subscripcion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscripcion.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscripcion.endpoint
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private String endpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscripcion.expirationTime
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    private String expirationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscripcion.id
     *
     * @return the value of subscripcion.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscripcion.id
     *
     * @param id the value for subscripcion.id
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscripcion.endpoint
     *
     * @return the value of subscripcion.endpoint
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public String getEndpoint() {
        return endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscripcion.endpoint
     *
     * @param endpoint the value for subscripcion.endpoint
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscripcion.expirationTime
     *
     * @return the value of subscripcion.expirationTime
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public String getExpirationtime() {
        return expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscripcion.expirationTime
     *
     * @param expirationtime the value for subscripcion.expirationTime
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setExpirationtime(String expirationtime) {
        this.expirationtime = expirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Subscripcion other = (Subscripcion) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEndpoint() == null ? other.getEndpoint() == null : this.getEndpoint().equals(other.getEndpoint()))
            && (this.getExpirationtime() == null ? other.getExpirationtime() == null : this.getExpirationtime().equals(other.getExpirationtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEndpoint() == null) ? 0 : getEndpoint().hashCode());
        result = prime * result + ((getExpirationtime() == null) ? 0 : getExpirationtime().hashCode());
        return result;
    }
}