package com.notiificaciones.push.domain.mysql;

import java.util.ArrayList;
import java.util.List;

public class SubscripcionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public SubscripcionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEndpointIsNull() {
            addCriterion("endpoint is null");
            return (Criteria) this;
        }

        public Criteria andEndpointIsNotNull() {
            addCriterion("endpoint is not null");
            return (Criteria) this;
        }

        public Criteria andEndpointEqualTo(String value) {
            addCriterion("endpoint =", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointNotEqualTo(String value) {
            addCriterion("endpoint <>", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointGreaterThan(String value) {
            addCriterion("endpoint >", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointGreaterThanOrEqualTo(String value) {
            addCriterion("endpoint >=", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointLessThan(String value) {
            addCriterion("endpoint <", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointLessThanOrEqualTo(String value) {
            addCriterion("endpoint <=", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointLike(String value) {
            addCriterion("endpoint like", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointNotLike(String value) {
            addCriterion("endpoint not like", value, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointIn(List<String> values) {
            addCriterion("endpoint in", values, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointNotIn(List<String> values) {
            addCriterion("endpoint not in", values, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointBetween(String value1, String value2) {
            addCriterion("endpoint between", value1, value2, "endpoint");
            return (Criteria) this;
        }

        public Criteria andEndpointNotBetween(String value1, String value2) {
            addCriterion("endpoint not between", value1, value2, "endpoint");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeIsNull() {
            addCriterion("expirationTime is null");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeIsNotNull() {
            addCriterion("expirationTime is not null");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeEqualTo(String value) {
            addCriterion("expirationTime =", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeNotEqualTo(String value) {
            addCriterion("expirationTime <>", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeGreaterThan(String value) {
            addCriterion("expirationTime >", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeGreaterThanOrEqualTo(String value) {
            addCriterion("expirationTime >=", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeLessThan(String value) {
            addCriterion("expirationTime <", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeLessThanOrEqualTo(String value) {
            addCriterion("expirationTime <=", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeLike(String value) {
            addCriterion("expirationTime like", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeNotLike(String value) {
            addCriterion("expirationTime not like", value, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeIn(List<String> values) {
            addCriterion("expirationTime in", values, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeNotIn(List<String> values) {
            addCriterion("expirationTime not in", values, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeBetween(String value1, String value2) {
            addCriterion("expirationTime between", value1, value2, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeNotBetween(String value1, String value2) {
            addCriterion("expirationTime not between", value1, value2, "expirationtime");
            return (Criteria) this;
        }

        public Criteria andEndpointLikeInsensitive(String value) {
            addCriterion("upper(endpoint) like", value.toUpperCase(), "endpoint");
            return (Criteria) this;
        }

        public Criteria andExpirationtimeLikeInsensitive(String value) {
            addCriterion("upper(expirationTime) like", value.toUpperCase(), "expirationtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscripcion
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 12 18:17:10 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}