package com.notiificaciones.push.domain.mysql;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsuarioSubscritoCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public UsuarioSubscritoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andRegistroIsNull() {
			addCriterion("registro is null");
			return (Criteria) this;
		}

		public Criteria andRegistroIsNotNull() {
			addCriterion("registro is not null");
			return (Criteria) this;
		}

		public Criteria andRegistroEqualTo(Date value) {
			addCriterion("registro =", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroNotEqualTo(Date value) {
			addCriterion("registro <>", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroGreaterThan(Date value) {
			addCriterion("registro >", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroGreaterThanOrEqualTo(Date value) {
			addCriterion("registro >=", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroLessThan(Date value) {
			addCriterion("registro <", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroLessThanOrEqualTo(Date value) {
			addCriterion("registro <=", value, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroIn(List<Date> values) {
			addCriterion("registro in", values, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroNotIn(List<Date> values) {
			addCriterion("registro not in", values, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroBetween(Date value1, Date value2) {
			addCriterion("registro between", value1, value2, "registro");
			return (Criteria) this;
		}

		public Criteria andRegistroNotBetween(Date value1, Date value2) {
			addCriterion("registro not between", value1, value2, "registro");
			return (Criteria) this;
		}

		public Criteria andSusbscritoIsNull() {
			addCriterion("susbscrito is null");
			return (Criteria) this;
		}

		public Criteria andSusbscritoIsNotNull() {
			addCriterion("susbscrito is not null");
			return (Criteria) this;
		}

		public Criteria andSusbscritoEqualTo(String value) {
			addCriterion("susbscrito =", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoNotEqualTo(String value) {
			addCriterion("susbscrito <>", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoGreaterThan(String value) {
			addCriterion("susbscrito >", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoGreaterThanOrEqualTo(String value) {
			addCriterion("susbscrito >=", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoLessThan(String value) {
			addCriterion("susbscrito <", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoLessThanOrEqualTo(String value) {
			addCriterion("susbscrito <=", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoLike(String value) {
			addCriterion("susbscrito like", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoNotLike(String value) {
			addCriterion("susbscrito not like", value, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoIn(List<String> values) {
			addCriterion("susbscrito in", values, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoNotIn(List<String> values) {
			addCriterion("susbscrito not in", values, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoBetween(String value1, String value2) {
			addCriterion("susbscrito between", value1, value2, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andSusbscritoNotBetween(String value1, String value2) {
			addCriterion("susbscrito not between", value1, value2, "susbscrito");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIsNull() {
			addCriterion("player_id is null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIsNotNull() {
			addCriterion("player_id is not null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdEqualTo(String value) {
			addCriterion("player_id =", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotEqualTo(String value) {
			addCriterion("player_id <>", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThan(String value) {
			addCriterion("player_id >", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThanOrEqualTo(String value) {
			addCriterion("player_id >=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThan(String value) {
			addCriterion("player_id <", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThanOrEqualTo(String value) {
			addCriterion("player_id <=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLike(String value) {
			addCriterion("player_id like", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotLike(String value) {
			addCriterion("player_id not like", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIn(List<String> values) {
			addCriterion("player_id in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotIn(List<String> values) {
			addCriterion("player_id not in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdBetween(String value1, String value2) {
			addCriterion("player_id between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotBetween(String value1, String value2) {
			addCriterion("player_id not between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andNombreLikeInsensitive(String value) {
			addCriterion("upper(nombre) like", value.toUpperCase(), "nombre");
			return (Criteria) this;
		}

		public Criteria andSusbscritoLikeInsensitive(String value) {
			addCriterion("upper(susbscrito) like", value.toUpperCase(), "susbscrito");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLikeInsensitive(String value) {
			addCriterion("upper(player_id) like", value.toUpperCase(), "playerId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuarios_subscritos
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 16 14:32:15 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}