package com.notiificaciones.push.domain.mysql;

import java.util.Date;

public class UsuarioSubscrito {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios_subscritos.id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios_subscritos.nombre
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios_subscritos.registro
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	private Date registro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios_subscritos.susbscrito
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	private String susbscrito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuarios_subscritos.player_id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	private String playerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios_subscritos.id
	 * @return  the value of usuarios_subscritos.id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios_subscritos.id
	 * @param id  the value for usuarios_subscritos.id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios_subscritos.nombre
	 * @return  the value of usuarios_subscritos.nombre
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios_subscritos.nombre
	 * @param nombre  the value for usuarios_subscritos.nombre
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios_subscritos.registro
	 * @return  the value of usuarios_subscritos.registro
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public Date getRegistro() {
		return registro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios_subscritos.registro
	 * @param registro  the value for usuarios_subscritos.registro
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setRegistro(Date registro) {
		this.registro = registro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios_subscritos.susbscrito
	 * @return  the value of usuarios_subscritos.susbscrito
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public String getSusbscrito() {
		return susbscrito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios_subscritos.susbscrito
	 * @param susbscrito  the value for usuarios_subscritos.susbscrito
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setSusbscrito(String susbscrito) {
		this.susbscrito = susbscrito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuarios_subscritos.player_id
	 * @return  the value of usuarios_subscritos.player_id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public String getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuarios_subscritos.player_id
	 * @param playerId  the value for usuarios_subscritos.player_id
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	public void setPlayerId(String playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UsuarioSubscrito other = (UsuarioSubscrito) that;
		return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
				&& (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
				&& (this.getRegistro() == null ? other.getRegistro() == null
						: this.getRegistro().equals(other.getRegistro()))
				&& (this.getSusbscrito() == null ? other.getSusbscrito() == null
						: this.getSusbscrito().equals(other.getSusbscrito()))
				&& (this.getPlayerId() == null ? other.getPlayerId() == null
						: this.getPlayerId().equals(other.getPlayerId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
		result = prime * result + ((getRegistro() == null) ? 0 : getRegistro().hashCode());
		result = prime * result + ((getSusbscrito() == null) ? 0 : getSusbscrito().hashCode());
		result = prime * result + ((getPlayerId() == null) ? 0 : getPlayerId().hashCode());
		return result;
	}
}