package com.notiificaciones.push.domain.mysql;

public class Usuario {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.id
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.username
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuario.clave
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    private String clave;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.id
     *
     * @return the value of usuario.id
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.id
     *
     * @param id the value for usuario.id
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.username
     *
     * @return the value of usuario.username
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.username
     *
     * @param username the value for usuario.username
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuario.clave
     *
     * @return the value of usuario.clave
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public String getClave() {
        return clave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuario.clave
     *
     * @param clave the value for usuario.clave
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Usuario other = (Usuario) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getClave() == null ? other.getClave() == null : this.getClave().equals(other.getClave()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getClave() == null) ? 0 : getClave().hashCode());
        return result;
    }
}