package com.notiificaciones.push.dao.mysql;

import com.notiificaciones.push.domain.mysql.Key;
import com.notiificaciones.push.domain.mysql.KeyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    long countByExample(KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int deleteByExample(KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int insert(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int insertSelective(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    List<Key> selectByExampleWithBLOBs(KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    List<Key> selectByExample(KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    Key selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByExampleSelective(@Param("record") Key record, @Param("example") KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Key record, @Param("example") KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByExample(@Param("record") Key record, @Param("example") KeyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByPrimaryKeySelective(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByPrimaryKeyWithBLOBs(Key record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByPrimaryKey(Key record);
}