package com.notiificaciones.push.dao.mysql;

import com.notiificaciones.push.domain.mysql.Subscripcion;
import com.notiificaciones.push.domain.mysql.SubscripcionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubscripcionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    long countByExample(SubscripcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int deleteByExample(SubscripcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int insert(Subscripcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int insertSelective(Subscripcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    List<Subscripcion> selectByExample(SubscripcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    Subscripcion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByExampleSelective(@Param("record") Subscripcion record, @Param("example") SubscripcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByExample(@Param("record") Subscripcion record, @Param("example") SubscripcionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByPrimaryKeySelective(Subscripcion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscripcion
     *
     * @mbg.generated Tue Sep 12 18:17:10 COT 2017
     */
    int updateByPrimaryKey(Subscripcion record);
}