package com.notiificaciones.push.dao.mysql;

import com.notiificaciones.push.domain.mysql.Usuario;
import com.notiificaciones.push.domain.mysql.UsuarioCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    long countByExample(UsuarioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int deleteByExample(UsuarioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int insert(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int insertSelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    List<Usuario> selectByExample(UsuarioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    Usuario selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int updateByExampleSelective(@Param("record") Usuario record, @Param("example") UsuarioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int updateByExample(@Param("record") Usuario record, @Param("example") UsuarioCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int updateByPrimaryKeySelective(Usuario record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuario
     *
     * @mbg.generated Sun Sep 17 00:14:12 COT 2017
     */
    int updateByPrimaryKey(Usuario record);
}