package com.notiificaciones.push.dao.mysql;

import com.notiificaciones.push.domain.mysql.UsuarioSubscrito;
import com.notiificaciones.push.domain.mysql.UsuarioSubscritoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuarioSubscritoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	long countByExample(UsuarioSubscritoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int deleteByExample(UsuarioSubscritoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int insert(UsuarioSubscrito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int insertSelective(UsuarioSubscrito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	List<UsuarioSubscrito> selectByExample(UsuarioSubscritoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	UsuarioSubscrito selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int updateByExampleSelective(@Param("record") UsuarioSubscrito record,
			@Param("example") UsuarioSubscritoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int updateByExample(@Param("record") UsuarioSubscrito record, @Param("example") UsuarioSubscritoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int updateByPrimaryKeySelective(UsuarioSubscrito record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuarios_subscritos
	 * @mbg.generated  Sat Sep 16 14:44:57 COT 2017
	 */
	int updateByPrimaryKey(UsuarioSubscrito record);
}